### ISSUE TITLE
Journalposter som lukkes blir ikke ferdigstilt?

### ISSUE THREAD

**Issue by albrektsson** [navikt/k9-punsj#919]
Fikse ALLT
```[tasklist]
### Tasks
- [x] Fikse i punsj
- [ ] Fikse i k9sak
- [ ] Fikse fikse
- [ ] TESTTESTTESTTESTTESTTEST
```

```[tasklist]
### Relaterade oppgaver - annenn apppp
- [ ] Do stuff, kanske fikse #918 ?
- [ ] Fiks https://github.com/navikt/k9-punsjbolle/pull/182 ?
- [ ] https://github.com/navikt/k9-punsjbolle/pull/182
- [ ] https://github.com/navikt/k9-vaktmester/issues/114
```
